#pragma once
#define HEIGHT 500
#define WIDTH 800
#define MACHINETIMER 500
#define NEWMACHINESNUMBER 3
#define HUMANDELAY 1
#define MACHINEDELAY 2
#define BULLET_DELAY 1
#define BULLET_TIMER 50
#define NEW_BULLET_NUMBER 1
#define START_PORT 8888